#pragma once
#include <fstream>
#include <iostream>
#include <string>
#include <sstream>
#include <algorithm>
#include <iterator>
#include <vector>
#include <iomanip> 
#include <vcclr.h>
#include <msclr\marshal_cppstd.h>
#include <Windows.h>